name: Setup project
description: Setup this project

runs:
  using: composite
  steps:
    -
      uses: pnpm/action-setup@v2
    -
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: pnpm
        registry-url: https://npm.pkg.github.com/
        scope: "@sun-yryr"
    -
      shell: bash
      run: pnpm install
