apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: discordbot
  name: discordbot-downloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: downloader
  template:
    metadata:
      labels:
        app: downloader
    spec:
      containers:
        - name: downloader
          image: ghcr.io/sun-yryr/discordbot-downloader:0.0.5
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord
                  key: token
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: discord
                  key: client_id
            - name: DOWNLOAD_DIR
              value: '/downloads'
          volumeMounts:
            - mountPath: /downloads
              name: sync_download_volume
        - name: sync
          image: ubuntu:22.04
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          volumeMounts:
            - mountPath: /downloads
              name: sync_download_volume
      volumes:
        - name: sync_download_volume
          emptyDir: {}
